library/catalog/urls.py
from . import views
from django.urls import path

#app_name = 'catalog'

urlpatterns = [
  path('',views.index,name="index"),
  path('create_book/',views.BookCreate.as_view(),name='create_book'),
  path('book_detail/<int:pk>',views.BookDetail.as_view(),name='book_detail'),
  path('my_view/',views.my_view,name='my_view'),
  path('signup/',views.SignUpForm.as_view(),name='signup'),
  path('profile/',views.ProfileView.as_view(),name='profile')
]

library/library/urls.py
from django import urls
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path,include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/',include('catalog.urls')),
    path('',RedirectView.as_view(url='catalog/')),
    path('accounts/',include('django.contrib.auth.urls'))
]

library/catalog/models.py
from argparse import _MutuallyExclusiveGroup
from django.urls import reverse
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Genre(models.Model):
  name = models.CharField(max_length=100)
  
  def __str__(self):
    return self.name

class Language(models.Model):
  name = models.CharField(max_length=100)

  def __str__(self):
    return self.name

class Book(models.Model):
  title = models.CharField(max_length=100)
  author = models.ForeignKey("Author",on_delete=models.SET_NULL,null=True)
  summary = models.TextField(max_length=1000)
  isbn = models.CharField("ISBN",max_length=13,unique=True)
  genre = models.ManyToManyField(Genre)
  language = models.ForeignKey("Language",on_delete=models.SET_NULL,null=True)

  def get_absolute_url(self):
    return reverse("book_detail",kwargs={"pk":self.pk})

  def __str__(self):
    return self.title

class Author(models.Model):
  first_name = models.CharField(max_length=30)
  last_name = models.CharField(max_length=30)
  date_of_birth = models.DateField(null=True,blank=True)

  class Meta:
    ordering = ['last_name','first_name']

  def get_absolute_url(self):
    return reverse("author_detail",kwargs={"pk":self.pk})

  def __str__(self):
    return f"{self.last_name}, {self.first_name} born on {self.date_of_birth}"

import uuid

class BookInstance(models.Model):
  id = models.UUIDField(default = uuid.uuid4, primary_key=True)
  book = models.ForeignKey("Book",on_delete=models.RESTRICT,null=True,blank=True)
  imprint = models.CharField(max_length=100)
  due_date = models.DateField(null=True,blank=True)
  borrower = models.ForeignKey(User,on_delete=models.SET_NULL,null=True,blank=True)

  LOAN_STATUS = (
    ('m','Maintainance'),
    ('o','On Loan'),
    ('r','Restricted'),
    ('a','Available')
  )

  status = models.CharField(choices=LOAN_STATUS,max_length=1,blank=True,default='a')

  class Meta:
    ordering = ['due_date']

  def __str__(self):
    return f'{self.id} ({self.book.title})'

library/catalog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Book,BookInstance
from django.views.generic import CreateView,DetailView,ListView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView
from django.urls import reverse_lazy
from django.contrib.auth.forms import UserCreationForm

def index(request):
  num_books = Book.objects.all().count()
  num_instance = BookInstance.objects.all().count()
  num_instances_available = BookInstance.objects.filter(status__exact='a').count()

  context = {
    'num_books':num_books,
    'num_instance':num_instance,
    'num_instances_available':num_instances_available
  }
  
  return render(request,'catalog/index.html',context=context)

class BookCreate(LoginRequiredMixin,CreateView):
  model = Book
  fields = '__all__'

class BookDetail(DetailView):
  model = Book

@login_required
def my_view(request):
  return render(request,'catalog/my_view.html')

class SignUpForm(CreateView):
  form_class = UserCreationForm
  success_url = reverse_lazy('login')
  template_name = "catalog/signup.html"

class ProfileView(ListView):
  model = BookInstance
  paginate_by = 5
  template_name = 'catalog/profile.html'

  def get_queryset(self):
    return BookInstance.objects.filter(borrower=self.request.user).all()

library/catalog/templates/catalog/book_detail.html
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>Detail View of {{book.title}}</h1>
  {{book}}
</body>
</html>

library/catalog/templates/catalog/book_form.html
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>Create New Book</h1>
  <form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="CREATE">
  </form>
</body>
</html>

library/catalog/templates/catalog/index.html
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>Index Page</h1>
  <p>Number of Books: {{num_books}}</p>
  <p>Number of Available Books: {{num_instances_available}}</p>

  {% if user.is_authenticated %}
  <p> You are logged in!</p>
  <p> Welcome : {{user.get_username}}</p>

  <a href="{% url 'logout' %}?next={{request.path}}">LOGOUT</a>

  {% else %}
  <p> You are not logged in!</p>

  <a href="{% url 'login' %}?next={{request.path}}">LOGIN</a>
  {% endif %}
</body>
</html>

library/catalog/templates/catalog/my_view.html
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>ONLY LOGGED IN USERS CAN ENTER!</h1>
</body>
</html>

library/catalog/templates/catalog/profile.html
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>Welcome to your Profile : {{user.get_username}}</h1>
  <p>Here are your books</p>
  {% for bookinstance in bookinstance_list %} 
  <p>{{bookinstance}}</p>
  {% endfor %}
</body>
</html>

library/catalog/templates/catalog/signup.html
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>Register New User</h1>
  <form method="post">
    {% csrf_token %} 
    {{form.as_p}}
    <input type="submit" value="Signup">
  </form>
</body>
</html>